DEEPGRAM_KEY=70187200ed45f0adca6eca8a3f99ebc7127b1f1d
OPENAPI_KEY=org-d9LqDSTnPM9E7scwPh4B66ft
run:
	python voice_bot_cli.py --stt-api-key ${DEEPGRAM_KEY} --tts-api-key ${OPENAPI_KEY} --llm-api-key ${OPENAPI_KEY}
